### ISSUE TITLE
Serve /site-static/ in addition to /static/

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-nginx#5]
Our docker-compose config mounts the folder already:

```yaml
  nginx:
    image: addons/addons-nginx
    volumes:
      - ./static:/srv/static
      - ./site-static:/srv/site-static
      - ./user-media/:/srv/user-media
```

So the nginx container should support this too.
